[pytest]
addopts = --ignore="tests/acceptance/fixtures"
filterwarnings =
    ignore:'asyncio\.iscoroutinefunction' is deprecated and slated for removal in Python 3\.16.*:DeprecationWarning
    ignore:'asyncio\.get_event_loop_policy' is deprecated and slated for removal in Python 3\.16.*:DeprecationWarning
    ignore:datetime\.datetime\.utcnow\(\) is deprecated and scheduled for removal in a future version.*:DeprecationWarning
    ignore:cannot collect test class 'TestFixRerunLoop' because it has a __init__ constructor:pytest.PytestCollectionWarning
    ignore:cannot collect test class 'TestScenario' because it has a __init__ constructor:pytest.PytestCollectionWarning
    ignore:cannot collect test class 'TestStatus' because it has a __new__ constructor:pytest.PytestCollectionWarning
    ignore:cannot collect test class 'TestResult' because it has a __init__ constructor:pytest.PytestCollectionWarning
    ignore:cannot collect test class 'TestSuiteResult' because it has a __init__ constructor:pytest.PytestCollectionWarning