name: mini-devin
region: blr

services:
  - name: backend
    github:
      repo: naimprince010-ship-it/mini-devin
      branch: main
      deploy_on_push: true
    source_dir: /
    dockerfile_path: Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 30
    envs:
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: "REPLACE_WITH_YOUR_KEY"
      - key: LLM_MODEL
        scope: RUN_TIME
        value: gpt-4o-mini
      - key: PORT
        scope: RUN_TIME
        value: "8000"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: "sqlite:///./minidevin.db"
