"""Add users and api_keys tables

Revision ID: a4fa26d3994c
Revises: ea6729d36c62
Create Date: 2025-12-16 07:59:07.097208

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a4fa26d3994c"
down_revision: Union[str, Sequence[str], None] = "ea6729d36c62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    insp = sa.inspect(bind)
    tables = set(insp.get_table_names())

    # ### commands auto generated by Alembic - please adjust! ###
    if "users" not in tables:
        op.create_table(
            "users",
            sa.Column("id", sa.String(length=36), nullable=False),
            sa.Column("email", sa.String(length=256), nullable=False),
            sa.Column("username", sa.String(length=128), nullable=False),
            sa.Column("hashed_password", sa.String(length=256), nullable=False),
            sa.Column("is_active", sa.Boolean(), nullable=False),
            sa.Column("is_admin", sa.Boolean(), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
        op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)

    if "api_keys" not in tables:
        op.create_table(
            "api_keys",
            sa.Column("id", sa.String(length=36), nullable=False),
            sa.Column("user_id", sa.String(length=36), nullable=False),
            sa.Column("name", sa.String(length=128), nullable=False),
            sa.Column("key_hash", sa.String(length=256), nullable=False),
            sa.Column("key_prefix", sa.String(length=8), nullable=False),
            sa.Column("is_active", sa.Boolean(), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("key_hash"),
        )

    if "sessions" in tables:
        col_names = {c["name"] for c in insp.get_columns("sessions")}
        if "user_id" not in col_names:
            op.add_column("sessions", sa.Column("user_id", sa.String(length=36), nullable=True))
        insp_fk = sa.inspect(bind)
        fks = insp_fk.get_foreign_keys("sessions")

        def _fk_cols(fk: dict) -> tuple[str, ...]:
            cc = fk.get("constrained_columns") or ()
            return tuple(str(c) for c in cc)

        has_user_fk = any(
            fk.get("referred_table") == "users" and _fk_cols(fk) == ("user_id",) for fk in fks
        )
        if not has_user_fk:
            op.create_foreign_key(None, "sessions", "users", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.drop_column("sessions", "user_id")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
